vim.filetype.add {
  pattern = {
    ["docker%-compose%.%w+%.ya?ml"] = "yaml.docker-compose",
    ["compose%.ya?ml"] = "yaml.docker-compose",
    ["docker-compose%.ya?ml"] = "yaml.docker-compose",
    [".*/%.github[%w/]+workflows[%w/]+.*%.ya?ml"] = "yaml.github",
    [".*/kustomization%.ya?ml"] = "yaml.kustomize",
    [".*/templates/.*%.ya?ml"] = "helm",
    [".*/templates/.*%.tpl"] = "helm",
    [".*/values%.ya?ml"] = "yaml.helm-values",
    [".*/values%-.+%.ya?ml"] = "yaml.helm-values",
    [".*/playbooks/.*%.ya?ml"] = "yaml.ansible",
    [".*/roles/.*/tasks/.*%.ya?ml"] = "yaml.ansible",
    [".*/roles/.*/handlers/.*%.ya?ml"] = "yaml.ansible",
    [".*/roles/.*/vars/.*%.ya?ml"] = "yaml.ansible",
    [".*/roles/.*/defaults/.*%.ya?ml"] = "yaml.ansible",
    [".*/k8s/.*%.ya?ml"] = "yaml.kubernetes",
    [".*/kubernetes/.*%.ya?ml"] = "yaml.kubernetes",
    [".*/manifests/.*%.ya?ml"] = "yaml.kubernetes",
    [".*/manifest/.*%.ya?ml"] = "yaml.kubernetes",
    [".*/deploy/.*%.ya?ml"] = "yaml.kubernetes",
    [".*/deployment/.*%.ya?ml"] = "yaml.kubernetes",
    [".*/base/.*%.ya?ml"] = "yaml.kubernetes",
    [".*/overlays/.*%.ya?ml"] = "yaml.kubernetes",
  },
}
