vim.cmd "syntax on"
vim.opt.laststatus = 3
vim.opt.splitkeep = "screen"
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.autoread = true
vim.opt.cursorcolumn = false
vim.opt.cursorline = true
vim.opt.expandtab = true
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.cindent = true
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.listchars = { tab = "» ", trail = "·", nbsp = "␣" }
vim.opt.list = true
vim.opt.mouse = "a"
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.shiftwidth = 2
vim.opt.shortmess:append "I"
vim.opt.showcmd = true
vim.opt.smartcase = true
vim.opt.swapfile = false
vim.opt.tabstop = 2
vim.opt.wildcharm = 26
vim.opt.wildignorecase = true
vim.opt.wildignore = "*.o,*.obj,*~,*.swp,*.git,*.hg,*.svn,*.DS_Store"
vim.opt.wildmenu = true
vim.opt.wildmode = "longest:full,full"
vim.opt.wildoptions = "pum"
vim.opt.wrap = true
vim.o.scl = "yes"
